### ISSUE TITLE
ImportError: cannot import name 'escape' from 'cgi'

### ISSUE THREAD

**Issue by Prn-Ice** [benjaoming/rhythmbox-fullscreen#9]
When I enable the plugin I get:
```sh
Traceback (most recent call last):
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/havoc/.local/share/rhythmbox/plugins/RhythmboxFullscreen/RhythmboxFullscreen.py", line 28, in <module>
    import FullscreenWindow
  File "/home/havoc/.local/share/rhythmbox/plugins/RhythmboxFullscreen/FullscreenWindow.py", line 25, in <module>
    from CairoWidgets import FullscreenEntryButton
  File "/home/havoc/.local/share/rhythmbox/plugins/RhythmboxFullscreen/CairoWidgets.py", line 20, in <module>
    from cgi import escape
ImportError: cannot import name 'escape' from 'cgi' (/usr/lib/python3.8/cgi.py)

(rhythmbox:20680): libpeas-WARNING **: 17:39:40.669: Error loading plugin 'RhythmboxFullscreen'
```

**Comment by benjaoming** [comment]
Thanks for reporting this! It's fixed now. I'm not sure if there are any packagers around who can release a .deb, but as you can see, it's reasonably easy to install yourself.
